apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: vasanthsumanath-co-in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vasanthsumanath.co.in
  dnsNames:
    - vasanthsumanath.co.in
    - www.vasanthsumanath.co.in
